<?php

namespace AppBundle\Repository;

/**
 * Cartomak_productRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cartomak_productRepository extends \Doctrine\ORM\EntityRepository
{
}
