<?php

namespace AppBundle\Repository;

/**
 * cartomak_product_dataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cartomak_product_dataRepository extends \Doctrine\ORM\EntityRepository
{
}
