<?php

namespace AppBundle\Repository;

/**
 * Cartomak_product_dataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cartomak_product_dataRepository extends \Doctrine\ORM\EntityRepository
{
}
