<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXbxlasf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXbxlasf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXbxlasf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXbxlasf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXbxlasf\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xbxlasf',
    'container.build_id' => '8db59428',
    'container.build_time' => 1542363687,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXbxlasf');
